'use client'
import { useEffect,useState } from 'react'
import { createClient } from '../../lib/supabase/client'
import { useRouter } from 'next/navigation'

export default function Onboarding(){const [form,setForm]=useState({name:'ABC Roofing Ltd',industry:'Roofing',services:'Roof repairs\nFull roof replacements\nFlat roofs\nGuttering & fascia',areas:'Southampton\nPortsmouth\nFareham\nWinchester',rules:'Prioritise urgent leaks, customers ready for a quote, and jobs within 6 weeks. Ask for postcode, property type, service required and timescale.',greeting:'Hi, I’m the AI Sales Assistant for ABC Roofing. How can I help today?'});const [busy,setBusy]=useState(false),[error,setError]=useState('');const router=useRouter();const sb=createClient()
useEffect(()=>{(async()=>{const {data:{user}}=await sb.auth.getUser();if(!user)router.push('/login')})()},[])
function set(k,v){setForm(f=>({...f,[k]:v}))}
async function save(e){e.preventDefault();setBusy(true);setError('');const r=await fetch('/api/onboarding',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(form)});const data=await r.json();setBusy(false);if(!r.ok){setError(data.error||'Could not create assistant');return}router.push('/dashboard')}
return <main className="auth"><form className="onboard" onSubmit={save}><div className="logo">LP</div><h1>Set up your first AI employee</h1><p>Everything here is editable later. We are starting with the sales assistant because it is the core product.</p><label>Business name<input value={form.name} onChange={e=>set('name',e.target.value)}/></label><label>Industry<input value={form.industry} onChange={e=>set('industry',e.target.value)}/></label><label>Services<textarea value={form.services} onChange={e=>set('services',e.target.value)}/></label><label>Areas covered<textarea value={form.areas} onChange={e=>set('areas',e.target.value)}/></label><label>Qualification rules<textarea value={form.rules} onChange={e=>set('rules',e.target.value)}/></label><label>Opening message<textarea value={form.greeting} onChange={e=>set('greeting',e.target.value)}/></label>{error&&<div className="error">{error}</div>}<button disabled={busy}>{busy?'Creating...':'Create AI assistant'}</button></form></main>}
